<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * QCMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QCMRepository extends EntityRepository {
  /**
   * @return nombre de qcm
   */
  public function count() {
    $qb = $this->createQueryBuilder('t');
    return $qb
      ->select('count(t.id)')
      ->getQuery()
      ->getSingleScalarResult();
  }

  /**
   * @return question
   */
  public function findQuestionsBy($id) {
    $qb = $this->createQueryBuilder('t');
    return $qb
      ->select('t.id, t.question, t.choix1, t.choix2, t.choix3')
      ->where("t.id = $id")
      ->getQuery()
      ->getSingleResult();
  }

  public function findReponseBy($id) {
    $qb = $this->createQueryBuilder('t');
    return $qb
      ->select('t.id, t.reponse, t.texte')
      ->where("t.id = $id")
      ->getQuery()
      ->getSingleResult();
  }

  /**
   * @param Request $request
   * NB : $request->query pour GET
   *    $request->request pour POST
   */
  public function getCurrentQCM(Request $request) {
  }
}
