contact:
    resource: "@ContactBundle/Controller/"
    type:     annotation
    prefix:   /

my:
    resource: "@MyBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation