security:

    encoders:
        WeeBundle\Entity\User: bcrypt

    providers:
        user_provider:
            entity:
                class: Weebundle\Entity\User
                property: email

    firewalls:
        # disables authentication for assets and the profiler
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            guard:
                authenticators:
                    - app.security.login_form_authenticator

            logout:
                path:  /logout