<?php

namespace WeeBundle\Repository;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends \Doctrine\ORM\EntityRepository {
  public function findAllBooksAuthor() {
    return $this
      ->createQueryBuilder('1')
      ->leftJoin('1.auteur', 'a')
      ->addSelect('a')
      ->getQuery()
      ->getResult();
  }
}
